### ISSUE TITLE
Option for clearing userInput onFailure()

### ISSUE THREAD

**Issue by dvadell** [talut/react-native-pin-view#1]
Hi,

It would be great to have an option to clear userInput (and/or this.state.animatedInputIndex, and then the circles in the upper side) when onFailure.

I think that it can be done in index.js, in keyboardOnPress, before calling onFailure. Something like  

```
this.userInput = []
this.setState({
          animatedInputIndex: []
});
```
Thanks for this module!

**Comment by talut** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [g](https://trello.com/c/WkkvAr7v/2-g)

**Comment by devcer** [comment]
Submitted a PR: https://github.com/talut/react-native-pin-view/pull/2
