### ISSUE TITLE
Add prop to not hide inputs

### ISSUE THREAD

**Issue by aarjae** [talut/react-native-pin-view#13]
This is a great component, but it will be nice if you added a prop so we don't hide the characters that are inputted. It will allow for use in much broader situations instead of just entering a pin

**Comment by talut** [comment]
Thanks 😃 That's a good idea. But this week I'm not able to adding this feature. But I think next week, I'll update & review all my packages and I'll added this feature.

**Comment by aarjae** [comment]
That's great! :+1:

**Comment by talut** [comment]
Issue solved: -- https://github.com/talut/react-native-pin-view/releases/tag/2.1.11

`showInputs={true|false}`
