### ISSUE TITLE
Fill last circle before onComplete event

### ISSUE THREAD

**Issue by hosseinpro** [talut/react-native-pin-view#14]
I put PinView in a modal screen and hide the modal screen in onComplete event. Every thing is ok but PinView raise onComplete just after pressing last number button without filling the last circle.

How can I solve that?

**Comment by talut** [comment]
Hi, yes onComplete is calling after last number clicked. After this,  state is updating and filling last circle. So, I think I can change this method to calling onComplete after state updated. 
I can't update because of the job intensity. But I'll look at this.


Thanks.

**Comment by hosseinpro** [comment]
Thank you.

**Comment by talut** [comment]
Hi, I added a props for this issue. if you update package to **v2.1.0** you can set **delayBeforeOnComplete** right now default value is 175ms

**Comment by hosseinpro** [comment]
Thank you. I checked that but I get the onComplete event with a big waiting more than 175ms.
On the other hand when I set delayBeforeOnComplete={0}, it works perfectly! The last circle is filled and then I get the onComplete event.
