### ISSUE TITLE
Adding text like "Enter your passcode"

### ISSUE THREAD

**Issue by hosseinpro** [talut/react-native-pin-view#15]
How can I add a message like "Enter your passcode"?

**Comment by hosseinpro** [comment]
I solved the problem by putting the PinView in another View (or Content in NativeBase).
`
  render() {
    return (
      <Modal
        animationType="slide"
        transparent={false}
        visible={this.state.visible}
        onRequestClose={() => {
          Alert.alert("Modal has been closed.");
        }}
      >
        <Content
          contentContainerStyle={{
            flex: 1,
            alignContent: "center",
            justifyContent: "center"
          }}
        >
          <Text
            style={{
              fontSize: 25,
              color: "red",
              alignSelf: "center",
              marginBottom: 20
            }}
          >
            Enter Passcode
          </Text>
          <PinView
            onComplete={(val, clear) => {
              clear();
              this.setState({ pinValue: val });
              this.setState({ visible: false });
            }}
            pinLength={4}
          />
          <Button
            transparent
            style={{
              alignSelf: "flex-end",
              marginRight: 60
            }}
            onPress={() => this.setState({ visible: false })}
          >
            <Text style={{ fontSize: 16 }}>Cancel</Text>
          </Button>
        </Content>
      </Modal>
    );
  }
`
<img width="292" alt="screen shot 2019-01-22 at 2 52 15 pm" src="https://user-images.githubusercontent.com/22692437/51561505-6e1da200-1e55-11e9-83c8-e9a73e1ed5fd.png">

**Comment by talut** [comment]
Hi , I think your Cancel button is for  your Modal. Not PinView package.
