### ISSUE TITLE
Pin View accepts more values than the PinLength attribute

### ISSUE THREAD

**Issue by burugular** [talut/react-native-pin-view#18]
Hello,
    In the PinView I am using pinLength attribute and I have set it to 5, the layout shows 5 which is good, but if I type more that 5 numbers it accepts it. Ideally it should only accept pinLength count of numbers right. 

here is an example.

```
   <PinView
              onComplete={(val, clear)=>{
                  alert(val); //if you press 12345678, it will alert definitely more than 5
                }
              }
              pinLength= 5
              buttonTextColor={colors.darkGrey}
              buttonBgColor={colors.lightestGrey}
              inputBgColor={colors.grey}
              inputActiveBgColor={colors.primaryColor}
              />
```

Am i missing anything to do here?

version : "react-native-pin-view": "^2.1.0",

Thanks
Rao

**Comment by talut** [comment]
@burugular Hey, thanks for issue. I'll look soon as possible.

**Comment by burugular** [comment]
@talut thank you very much

**Comment by burugular** [comment]
Hello @talut any update please. could you roughly let me know how long it might take to fix it. if it is too long I will find an temporary solution to take just the required digits

**Comment by talut** [comment]
@burugular Sorry for too long waiting. I'm full of with job/life schedule. Right now I can't find any time for this issue. But if I find I'll look as soon as possible.

**Comment by talut** [comment]
Issue solved -> https://github.com/talut/react-native-pin-view/releases/tag/2.1.11
