### ISSUE TITLE
[REQUEST] PinViewProps interface improvements

### ISSUE THREAD

**Issue by mihaidaviddev** [talut/react-native-pin-view#20]
onComplete
When the user completed input the pin, then inputted value will return. Also clear() is returning too. So if you want to remove user input after onComplete call clear() func in onComplete.

The onComplete property should be updated to include these parameters

```
 interface PinViewProps {
        pinLength?: number,
        showInputs?: boolean,
        inputTextStyle?: object,
        buttonTextColor?: string,
        returnType?: string,
        buttonBgColor?: string,
        inputBgColor?: string,
        onComplete: () => void,
        disabled?: boolean,
        inputActiveBgColor?: string,
        inputBgOpacity?: number,
        deleteText?: string
    }
```

**Comment by carlosroberto555** [comment]
I did try update onComplete on interface to:

```typescript
onComplete(val: string, clear: () => void): void
```
But I had this error on typescript:

> JSX element type 'Component<PinViewProps, {}, any>' is not a constructor function for JSX elements.
>
>   Type 'Component<PinViewProps, {}, any>' is missing the following properties from type 'Element': type, key

**Comment by mihaidaviddev** [comment]
I think it should be
```
onComplete: (val: string, clear: () => void) => void
```
I don't have any static type / runtime error. 
```
interface PinViewProps {
        pinLength?: number,
        showInputs?: boolean,
        inputTextStyle?: object,
        buttonTextColor?: string,
        returnType?: string,
        buttonBgColor?: string,
        inputBgColor?: string,
        onComplete: (val: string, clear: () => void) => void,
        disabled?: boolean,
        inputActiveBgColor?: string,
        inputBgOpacity?: number,
        deleteText?: string
    }
```

**Comment by talut** [comment]
https://github.com/talut/react-native-pin-view/pull/28
