### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by mattvick** [talut/react-native-pin-view#27]
Add an [ESLint configuration file](https://eslint.org/docs/user-guide/configuring) to the root of the project.

**Comment by talut** [comment]
Hi, thanks for all support, I can add an ESLint configuration file but do you have any example configuration file to suggest for rules? I'm using an ESLint configuration file generated by me at my own projects. But I think that file will not work good for everyone.

**Comment by mattvick** [comment]
It's a pleasure. Thanks for creating this package. I'm using the following on my projects.

```json
{
  "extends": [
    "airbnb"
  ],
  "plugins": [
    "react-hooks"
  ],
  "env": {
    "jest": true
  },
  "parser": "babel-eslint",
  "rules": {
    "semi": [
      "error",
      "always"
    ],
    "react/jsx-filename-extension": [
      1,
      {
        "extensions": [
          ".js",
          ".jsx"
        ]
      }
    ],
    "import/no-unresolved": [
      2,
      {
        "ignore": [
          "^NativeModules$"
        ]
      }
    ],
    "react-hooks/rules-of-hooks": "error",
    "react-hooks/exhaustive-deps": "warn"
  },
  "globals": {
    "__DEV__": "readonly"
  },
  "settings": {
    "import/resolver": {
      "node": {
        "extensions": [
          ".js",
          ".ios.js",
          ".android.js",
          ".jsx"
        ]
      }
    }
  }
}

```

**Comment by talut** [comment]
@mattvick I added config file. I hope it'll work. BTW, is ESLint config file necessary for normal usage? Because I don't want to upgrade the version of package for just ESLint file.
