### ISSUE TITLE
[REQUEST] Turn Delete from String into Icon ? 

### ISSUE THREAD

**Issue by devfordays** [talut/react-native-pin-view#30]
Is there a way to turn the delete from string into icon ?

**Comment by carlosroberto555** [comment]
You can use a ```react-native-vector-icons``` library, works fine for me
Example:
```jsx
import Icon from 'react-native-vector-icons/Ionicons'

<PinView
  // ... your props
  deleteText={<Icon name="ios-backspace" size={32} />}
/>
```

**Comment by talut** [comment]
Hi right now only these features added: https://github.com/talut/react-native-pin-view/pull/33

I'm considering writing this package with hooks and new features.
