### ISSUE TITLE
getting 7 digit while entering pin while  pinLength set to 6

### ISSUE THREAD

**Issue by behappiest** [talut/react-native-pin-view#34]
if we enter pin frequently then 
getting 7 digit while entering pin while pinLength set to 6
Screenshot attached
RN version
"react-native": "0.60.4",
 "react-native": "0.60.4",
"react-native-pin-view": "^2.3.1",

![Screenshot_1566652465](https://user-images.githubusercontent.com/13914594/63637871-651cd980-c69f-11e9-9935-411626da21da.png)

**Comment by eggzon** [comment]
Since you have version 2.3.1, i guess you can use onPress to disable pin button after length is 6

**Comment by mattvick** [comment]
This issue also causes the Del button to stop working if the when too many digits have been entered.

Pull request #35 resolves this
