### ISSUE TITLE
Emoji Keyboard

### ISSUE THREAD

**Issue by aadeshb7** [talut/react-native-pin-view#38]
Hey. I'm new to react-native and I'm creating an app which will verify the users by entering emoji's instead of normal number input. So could you please help me out with how the keyboard view can be changed to display certain emojis instead of the numbers. I would like to display 10 emojis instead of the numbers on the keyboard.
Thanks

**Comment by talut** [comment]
Hi, right now I don't think adding a feature like this. You can fork this repo and change for your feature.
