### ISSUE TITLE
Layout on smaller screen.

### ISSUE THREAD

**Issue by isohanvanani** [talut/react-native-pin-view#39]
**Describe the bug**
Layout not proper on smaller screen device, have a look at screenshot.

My code is as per below.
```
<PinView
                        buttonDeletePosition="right"
                        buttonBgColor="#f1f1f1"
                        onComplete={this.onPinSuccess}
                        pinLength={4} // You can also use like that.
                        
                    />
```
![Screenshot 2019-10-11 at 11 45 52 AM](https://user-images.githubusercontent.com/43265432/66628623-f8dd4180-ec1c-11e9-90b0-22637eb49615.png)

Device: iPhone SE

**Comment by talut** [comment]
Hi, right now v2.4.1 solving this issue with minor edit. But I'm rewriting this package and this styling issues will solved I hope :)
