### ISSUE TITLE
Warning when using Icon for deleteText

### ISSUE THREAD

**Issue by DianaKoenraadt** [talut/react-native-pin-view#40]
**Describe the bug**
Hi, thanks for your useful library! When we do as suggested in issue #30 we get the warning

`Warning: Failed prop type: Invalid prop `deleteText` of type `object` supplied to `PinView`, expected `string`.`

**To Reproduce**
Use `deleteText={<Icon name="ios-backspace" size={32} />}`

Rendering is ok, but a warning is present.

**Expected behavior**
No warnings.

**Device (please complete the following information):**
Expo SDK, Android Emulator for Nexus, API 28, Android 9.0

**Comment by talut** [comment]
Hi `deleteText` is using `<Text>` component so type definition for this component is string. But I think I forgot update type definition `string` to `any` I'll update as soon as possible.

**Comment by talut** [comment]
Please check v2.4.1
