### ISSUE TITLE
The delete button style does not change

### ISSUE THREAD

**Issue by hosseinpro** [talut/react-native-pin-view#49]
I tried to use the prop feature to change the delete button style but it does not work.

I use version 2.5.0 with the following prop:

`buttonDeleteStyle={<Icon name="ios-backspace" size={32} />}`

nothing happens.

**Comment by talut** [comment]
Hi, `buttonDeleteStyle` only accept style object not a component.

**Comment by hosseinpro** [comment]
I also tried this code but does not work.

`buttonDeleteStyle={{fontSize: 16}}`

**Comment by talut** [comment]
@hosseinpro  buttonDeleteStyle is changing style of delete button not delete button text. So you can't use fontSize etc.

**Comment by hosseinpro** [comment]
So, do you have an example of that?
For example, how can I hide the delete button permanently?

**Comment by talut** [comment]
> So, do you have an example of that?
> For example, how can I hide the delete button permanently?


There is no special props for changing delete button text style you can use keyboardViewTextStyle but this props changing all button text styles.

```
 keyboardViewTextStyle={{
            fontSize: 11,
          }}
```

There is no props for hiding the delete button.

**Comment by hosseinpro** [comment]
Thank you for the quick response.
So, can I change the color of the delete button? Do you have an example?

**Comment by talut** [comment]
> Thank you for the quick response.
> So, can I change the color of the delete button? Do you have an example?

You can change text color of buttons with `keyboardViewTextStyle` also you can change deleteButton background color with `buttonDeleteStyle`

**Comment by hosseinpro** [comment]
I tested this code but it does not work:

`buttonDeleteStyle={{ backgroundColor: "Green" }}`

What is the problem?

**Comment by talut** [comment]
> buttonDeleteStyle={{ backgroundColor: "Green" }}

"Green" > "green"

**Comment by hosseinpro** [comment]
> > buttonDeleteStyle={{ backgroundColor: "Green" }}
> 
> "Green" > "green"

same result. this is my code:

`<PinView
            onComplete={(pass, clear) => {
              clear();
              this.setState({ visible: false });
              this.state.onComplete(pass);
            }}
            pinLength={4}
            delayBeforeOnComplete={0}
            buttonBgColor={Colors.secondary}
            buttonTextColor={Colors.secondary}
            inputBgColor={Colors.primaryText}
            buttonDeleteStyle={{ backgroundColor: "green" }}
          />`

**Comment by talut** [comment]
<img width="339" alt="Screen Shot 2020-01-15 at 17 34 56" src="https://user-images.githubusercontent.com/7842301/72442372-69b46c80-37bd-11ea-868c-c055bb89104c.png">

```javascript
import React, { Component } from "react"
import { View } from "react-native"
import PinView from "react-native-pin-view"

type Props = {}
export default class Test extends Component<Props> {
  constructor(props) {
    super(props)
    this.onComplete = this.onComplete.bind(this)
    this.state = {
      pin: "896745",
    }
  }
  onComplete(inputtedPin, clear) {
    if (val !== this.state.pin) {
      clear()
    } else {
      console.log("Pin is correct")
    }
  }
  onPress(inputtedPin, clear, pressed) {
    console.log("Pressed: " + pressed)
    console.log("inputtedPin: " + inputtedPin)
    // clear();
  }
  render() {
    return (
      <View
        style={{
          flex: 1,
          backgroundColor: "#f1f1f1",
          justifyContent: "center",
        }}>
        <PinView
          onPress={this.onPress}
          onComplete={this.onComplete}
          buttonDeleteStyle={{ backgroundColor: "green" }}
          pinLength={this.state.pin.length}
          // pinLength={6} // You can also use like that.
        />
      </View>
    )
  }
}

```

**Comment by hosseinpro** [comment]
What version do you use? 2.4.1 or 2.5.0?

**Comment by talut** [comment]
`"react-native-pin-view": "^2.5.0",`

**Comment by hosseinpro** [comment]
Solved. I removed the "react-native-pin-view" package and installed it again.

**Comment by talut** [comment]
So I'm closing the issue if is K?

**Comment by hosseinpro** [comment]
yes. thank you.
