### ISSUE TITLE
Error callback is not a function

### ISSUE THREAD

**Issue by keryar** [talut/react-native-pin-view#51]
Hi
Everytime I click on a digit, I receive this error. 
```
Uncaught TypeError: callback is not a function
    at flushFirstCallback (scheduler.development.js:107)
    at flushWork (scheduler.development.js:219)
    at MessagePort.channel.port1.onmessage (scheduler.development.js:611)
flushFirstCallback @ scheduler.development.js:107
flushWork @ scheduler.development.js:219
channel.port1.onmessage @ scheduler.development.js:611

```

It breaks as an apk but on avd it is dismissable.

I upgraded to the version 3.0.0

This is my code:
```
<ReactNativePinView
                        inputSize={25}
                        ref={this.state.pinView}
                        pinLength={pinLen}
                        onButtonPress={key => { this.padHandler(key)
                          }}    
                          customLeftButton={this.state.showRemoveButton ? <Icon name={"backspace"} size={36} color={"#FFF"} />: undefined}
                          customRightButton={this.state.showUnlockButton ? <Icon name={"unlock"} size={36} color={"#FFF"} />: undefined}
                        />
```

Even if I remove the OnButtonPress, the problem continues

react-native info:
  React Native Environment Info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
      CPU: (8) x64 Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
      Memory: 192.19 MB / 7.66 GB
      Shell: 5.4.2 - /usr/bin/zsh
    Binaries:
      Node: 11.15.0 - ~/.nvm/versions/node/v11.15.0/bin/node
      Yarn: 1.21.1 - /usr/bin/yarn
      npm: 6.7.0 - ~/.nvm/versions/node/v11.15.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 23, 28
        Build Tools: 28.0.3
        System Images: android-28 | Google Play Intel x86 Atom
    npmPackages:
      react: 16.8.6 => 16.8.6 
      react-native: 0.59.6 => 0.59.6

**Comment by keryar** [comment]
Additional information:
This error also happens when the page first renders and when I remove the pin-pad, the error doesn't happen.

**Comment by talut** [comment]
Hi, I tried to run your code and I think you're trying create something like that and this is working well.

```javascript
import React from "react"
import { SafeAreaView, StatusBar } from "react-native"
import ReactNativePinView from "react-native-pin-view"
import Icon from "react-native-vector-icons/Ionicons"
class App extends React.Component {
  pinView = React.createRef()
  constructor(props) {
    super(props)
    this.state = {
      showRemoveButton: false,
      pinView: null,
      showUnlockButton: false,
    }
  }
  padHandler = key => {
    console.log(this.pinView)
    if (key === "custom_left") {
      this.pinView.current.clear()
    }
  }
  render() {
    return (
      <>
        <StatusBar barStyle="dark-content" />
        <SafeAreaView style={{ flex: 1, backgroundColor: "#FC0", justifyContent: "center" }}>
          <ReactNativePinView
            inputSize={25}
            onValueChange={value => {
              if (value.length > 0) {
                this.setState({ showRemoveButton: true })
              }
            }}
            ref={this.pinView}
            pinLength={8}
            onButtonPress={key => {
              this.padHandler(key)
            }}
            customLeftButton={
              this.state.showRemoveButton ? <Icon name="ios-backspace" size={36} color={"#FFF"} /> : undefined
            }
            customRightButton={
              this.state.showUnlockButton ? <Icon name="ios-unlock" size={36} color={"#FFF"} /> : undefined
            }
          />
        </SafeAreaView>
      </>
    )
  }
}
export default App

```

**Comment by keryar** [comment]
On the virtual device this doesn't crash me. But the problem is on the console. Every time I click on a key, it returns the error. And on the generated apk, the app crashes.

I just updated the code to be more similar to this yours but the problem persists.

I came across a solution that stated this might be a problem with some of react-native libraries being outdated.
[here](https://github.com/facebook/react/issues/16364)

I've installed many version of react-native but did not find the "right" one.

This is the error:
![image](https://user-images.githubusercontent.com/14828564/73195628-f55ac100-410c-11ea-8065-53e67b471f05.png)

**Comment by keryar** [comment]
These are my dependencies on package.json
`"dependencies": {
    "firebase": "^5.10.1",
    "native-base": "^2.12.1",
    "node-pre-gyp": "^0.13.0",
    "react": "^16.12.0",
    "react-native": "^0.59.6",
    "react-native-camera": "^2.6.0",
    "react-native-elements": "^1.1.0",
    "react-native-facebook-login": "^1.6.2",
    "react-native-fbsdk": "^0.8.0",
    "react-native-firebase": "^5.3.1",
    "react-native-gesture-handler": "^1.2.0",
    "react-native-google-signin": "^2.0.0",
    "react-native-image-picker": "^0.28.1",
    "react-native-linear-gradient": "^2.5.4",
    "react-native-pin-view": "^3.0.0",
    "react-native-vector-icons": "^6.4.2",
    "react-navigation": "^3.9.1"
  }`

**Comment by keryar** [comment]
I don't know if its related. But I used a transformation that rotated the keyboard 180 degrees and it made any version of the pinpad to be unresponsive in many devices.

**Comment by talut** [comment]
This problem not occurred when released on APK or IOS. If you still facing with this issue please open a new issue.
