### ISSUE TITLE
Hit exception "Unable to resolve "./libs/parts/KeyboardView"

### ISSUE THREAD

**Issue by sebastianlele1017** [talut/react-native-pin-view#52]
I have updated the react-native-pin-view from version 2.5.0 to 3.0.0 using command 'npm install react-native-pin-view@latest --save'. However, when I tried to run the project, it shows exception "Unable to resolve "./libs/parts/KeyboardView" from "node_modules\react-native-pin-view\index.js".  The code below shows the current version and dependencies for the package.

package.json :
"react-native-pin-view": "^3.0.0",

package-lock.json : 
"react-native-pin-view": {
      "version": "3.0.0",
      "resolved": "https://registry.npmjs.org/react-native-pin-view/-/react-native-pin-view-3.0.0.tgz",
      "integrity": "sha512-6REScMNTIjhdRs7JUe1wbpz19OM4BcpLRI3w/WIvNCWyLppZlUOE4qne5jsQziUefN5vFlvxyiT4NwrNgQy1Ig==",
      "requires": {
        "prop-types": "^15.7.2"
      }
    },

**Comment by talut** [comment]
Hi, you should remove node_modules and re-install with `npm install`. With v3.0.0 this package has only index.js and all files on `./libs/*` are removed. I think your 'node_modules' has a failed install process.

**Comment by sebastianlele1017** [comment]
Thanks...btw is it possible for enhancement such that allowing user to modify the styling of buttonContainer ? Now would like to change the marginBottom for the buttonContainer (currently fixed at 12) but found that there is no way to pass the customized styling to the container ?

**Comment by talut** [comment]
`buttonAreaStyle` for button container. 
`buttonViewStyle` for button view.
`buttonTextStyle` for button text.

**Comment by sebastianlele1017** [comment]
What attribute has replaced onComplete()?

**Comment by talut** [comment]
Please check example: https://github.com/talut/react-native-pin-view#example
This package is not controlling entered pin etc. only giving to inputted data with `onValueChange`or `onButtonPress`
