### ISSUE TITLE
buttonSize not being applied to "0" button

### ISSUE THREAD

**Issue by ericrabiner** [talut/react-native-pin-view#57]
**Describe the bug**
buttonSize not being applied to "0" button

**To Reproduce**
Set button size to something like buttonSize={100}

**Expected behavior**
"0" button should be size of 100

**Additional context**
In index.js buttonSize is being overwritten by customLeftButtonSize. I was able to set the button size to 100 by setting customLeftButtonSize=100. 

` <ViewButton
            disabled={disabled}
            accessible={accessible}
            activeOpacity={activeOpacity}
            onButtonPress={() => onButtonPressHandle("zero", "0")}
            buttonSize={buttonSize}
            text={buttonTextByKey.zero}
            customTextStyle={buttonTextStyle}
            customViewStyle={buttonViewStyle}
            buttonSize={customLeftButtonSize}
          />
`

**Comment by talut** [comment]
Please check new version.
