### ISSUE TITLE
Change font and "dot" style

### ISSUE THREAD

**Issue by davidmarinangeli** [talut/react-native-pin-view#6]
Hello, I am using your library and I am trying to use my personal style set for the PIN login. Do I have the possibility to change the default one? 

Thanks for your library! 🐸

**Comment by talut** [comment]
Hi, right now library not have a styling support like that. But I think I can do that. So right now you can fork my package and change style. But I will add these features as soon as possible. Thanks to you for using. I'm adding a To-Do card.

**Comment by davidmarinangeli** [comment]
Thanks a lot. I will do it and I hope to have also a pull request from you in the next days.

Happy Halloween 🎃

**Comment by vinhthieugia** [comment]
You can access into folder node_modules/react-native-pin-view/libs/parts/styles.js and change default styles of "passwordInputViewItem" and "keyboardViewItem".

**Comment by talut** [comment]
Issue solved with -> [https://github.com/talut/react-native-pin-view/releases/tag/2.2.0](https://github.com/talut/react-native-pin-view/releases/tag/2.2.0)

You can see new props from here : [https://github.com/talut/react-native-pin-view#props](https://github.com/talut/react-native-pin-view#props)

**Comment by vinhthieugia** [comment]
Oh thanks for notifying me about it. I will try in my project.

**Comment by talut** [comment]
No problem, I solved issue too early, didn't I? 😆 I hope it answers your needs.
